M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu22.04.1} date Sat 17 Jun 2023 09:55:33 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-17T21:55:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.8Y-2.9
X3.8Y-4.1
X5.6Y-2.9
X5.6Y-4.1
T0
M30
